<?php

namespace Gmas\MusicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsCategoryRepository extends EntityRepository
{
}
