fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

gmas_user_admin_users_list:
    pattern:  /admin/users/list
    defaults: { _controller: GmasUserBundle:User:admin_list }

gmas_user_admin_users_list_admins:
    pattern:  /admin/users/list/admins
    defaults: { _controller: GmasUserBundle:User:admin_list_admin }

gmas_user_admin_users_view:
    pattern:  /admin/users/view/{userid}
    defaults: { _controller: GmasUserBundle:User:admin_view }

gmas_user_admin_users_delete:
    pattern:  /admin/users/delete/{userid}
    defaults: { _controller: GmasUserBundle:User:admin_delete }

gmas_user_admin_users_validate:
    pattern:  /admin/users/validate/{userid}
    defaults: { _controller: GmasUserBundle:User:admin_validate }

gmas_user_admin_users_create:
    pattern:  /admin/users/create
    defaults: { _controller: GmasUserBundle:User:admin_create }
