gmas_remote:
    resource: "@GmasRemoteBundle/Controller/"
    type:     annotation
    prefix:   /

gmas_public:
    resource: "@GmasPublicBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: GmasMusicBundle:Song:index }

gmas_user:
    resource: "@GmasUserBundle/Resources/config/routing.yml"
    prefix:   /

gmas_music:
    resource: "@GmasMusicBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"